//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Earning
    {
        public int earning_id { get; set; }
        public int quantity { get; set; }
        public decimal rate { get; set; }
        public int earning_type_id { get; set; }
        public int payslip_id { get; set; }
        public Nullable<bool> taxable { get; set; }
    
        public virtual EarningType EarningType { get; set; }
        public virtual Payslip Payslip { get; set; }
    }
}
