//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExtermiconDBEntities : DbContext
    {
        public ExtermiconDBEntities()
            : base("name=ExtermiconDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Deduction> Deductions { get; set; }
        public DbSet<DeductionType> DeductionTypes { get; set; }
        public DbSet<Earning> Earnings { get; set; }
        public DbSet<EarningType> EarningTypes { get; set; }
        public DbSet<PayPeriod> PayPeriods { get; set; }
        public DbSet<PayPeriodType> PayPeriodTypes { get; set; }
        public DbSet<Payslip> Payslips { get; set; }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<tblHoliday> tblHolidays { get; set; }
        public DbSet<tblLogin> tblLogins { get; set; }
        public DbSet<tblRole> tblRoles { get; set; }
        public DbSet<tblSchedule> tblSchedules { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<vw_deduction_no_zero> vw_deduction_no_zero { get; set; }
        public DbSet<vw_earning_no_zero> vw_earning_no_zero { get; set; }
        public DbSet<vw_emp_user> vw_emp_user { get; set; }
        public DbSet<vw_emp_with_no_account> vw_emp_with_no_account { get; set; }
        public DbSet<vw_employee_list> vw_employee_list { get; set; }
        public DbSet<vw_log_in_history> vw_log_in_history { get; set; }
        public DbSet<vw_payslip_summary> vw_payslip_summary { get; set; }
        public DbSet<vw_schedule_list> vw_schedule_list { get; set; }
        public DbSet<vw_today_logs> vw_today_logs { get; set; }
        public DbSet<vw_user_schedule> vw_user_schedule { get; set; }
    }
}
