//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payslip
    {
        public Payslip()
        {
            this.Deductions = new HashSet<Deduction>();
            this.Earnings = new HashSet<Earning>();
        }
    
        public int payslip_id { get; set; }
        public System.DateTime issue_date { get; set; }
        public decimal COLA { get; set; }
        public decimal basic_rate { get; set; }
        public Nullable<System.DateTime> period_start { get; set; }
        public Nullable<System.DateTime> period_end { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<decimal> dayspresent { get; set; }
    
        public virtual ICollection<Deduction> Deductions { get; set; }
        public virtual ICollection<Earning> Earnings { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
