//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PH_DEDUCTIONSEntities : DbContext
    {
        public PH_DEDUCTIONSEntities()
            : base("name=PH_DEDUCTIONSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PagibigRate> PagibigRates { get; set; }
        public DbSet<PhilHealthRate> PhilHealthRates { get; set; }
        public DbSet<SalaryType> SalaryTypes { get; set; }
        public DbSet<SocialSecurityServiceRate> SocialSecurityServiceRates { get; set; }
        public DbSet<TaxDependentType> TaxDependentTypes { get; set; }
        public DbSet<WithHoldingTaxRate> WithHoldingTaxRates { get; set; }
    }
}
