//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhilHealthRate
    {
        public int philhealth_rate_id { get; set; }
        public Nullable<decimal> salary_flooring { get; set; }
        public Nullable<decimal> salary_ceiling { get; set; }
        public Nullable<decimal> employee_contribution { get; set; }
        public Nullable<decimal> employer_contribution { get; set; }
    }
}
