//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public tblEmployee()
        {
            this.Payslips = new HashSet<Payslip>();
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public int emp_id { get; set; }
        public string employee_number { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public string home_address { get; set; }
        public string email_address { get; set; }
        public byte[] photo { get; set; }
        public decimal basic_salary { get; set; }
        public string designation { get; set; }
        public string status { get; set; }
        public decimal cola { get; set; }
        public Nullable<int> tax_dependent_type_id { get; set; }
    
        public virtual ICollection<Payslip> Payslips { get; set; }
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
