//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchedule
    {
        public tblSchedule()
        {
            this.tblLogins = new HashSet<tblLogin>();
            this.tblUsers = new HashSet<tblUser>();
        }
    
        public int sched_id { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
    
        public virtual ICollection<tblLogin> tblLogins { get; set; }
        public virtual ICollection<tblUser> tblUsers { get; set; }
    }
}
