//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_earning_no_zero
    {
        public string name { get; set; }
        public int earning_type_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int payslip_id { get; set; }
        public int earning_id { get; set; }
    }
}
