//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_emp_user
    {
        public int emp_id { get; set; }
        public int user_id { get; set; }
        public byte[] photo { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string passcode { get; set; }
        public int sched_id { get; set; }
        public int role_id { get; set; }
        public string schedule { get; set; }
    }
}
