//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_log_in_history
    {
        public int log_id { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> sched_id { get; set; }
        public string date { get; set; }
        public Nullable<System.DateTime> dtstamp { get; set; }
        public string note { get; set; }
        public string schedule { get; set; }
        public Nullable<double> hours_spent { get; set; }
        public Nullable<double> hours_over { get; set; }
        public string name { get; set; }
        public string log { get; set; }
        public Nullable<int> emp_id { get; set; }
    }
}
