//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extermicon_Payroll_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithHoldingTaxRate
    {
        public int wth_rate_id { get; set; }
        public Nullable<int> salary_type_id { get; set; }
        public Nullable<int> tax_dependent_type_id { get; set; }
        public Nullable<decimal> exemption { get; set; }
        public Nullable<decimal> percent_over { get; set; }
        public Nullable<decimal> flooring { get; set; }
        public Nullable<decimal> ceiling { get; set; }
    
        public virtual SalaryType SalaryType { get; set; }
        public virtual TaxDependentType TaxDependentType { get; set; }
    }
}
